stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - sonarqube
  - cypress
  - docker

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test-job:       # This job runs in the build stage, which runs first.
  stage: test
  script:
    - ./gradlew test
    - ./gradlew.bat --stop

sonarqube-check:
  stage: sonarqube
  script:
    - ./gradlew sonarqube
    - ./gradlew.bat --stop


cypress_tests:  
  stage: cypress
  image: cypress/base:10
  script:
    - docker container run --name BudgetSimpleMySql mysql
    - docker container run --name BudgetSimpleBackend budgetsimplebackend
    - cd budgetsimple_front_end/react-hooks-crud
    - npx cypress run
    - cd ..
    - cd ..
    - docker stop BudgetSimpleBackend
    - docker stop BudgetSimpleMySql


docker:
  stage: docker
  script:
    - cd budgetsimple_front_end/react-hooks-crud
    - docker build -t budgetsimplefrontend .
    - cd ..
    - cd ..
    - replace "F:\stela\fontys\individual\budgetsimple_individual_project\override\prod\application.properties" "F:\stela\fontys\individual\budgetsimple_individual_project\src\main\resources"
    - replace "override/prod/application.properties" "src/main/resources"
    - ./gradlew build -x test
    - docker build -t budgetsimplebackend .
    - replace "F:\stela\fontys\individual\budgetsimple_individual_project\override\test\application.properties" "F:\stela\fontys\individual\budgetsimple_individual_project\src\main\resources"
    - replace "override/test/application.properties" "src/main/resources"
    - ./gradlew.bat --stop

