stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - sonarqube-check
  - cypress
  - docker

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test-job:       # This job runs in the build stage, which runs first.
  stage: test
  script:
    - ./gradlew test
    - ./gradlew.bat --stop

sonarqube-check:
  stage: sonarqube
  image: gradle:jre11-slim
  variables: 
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths: 
      - .sonar/cache  
    script: gradle sonarqube
    allow_failure: true
    only:
      - master

cypress_tests:  
  stage: cypress
  image: cypress/base:10
  script:    
    - cd budgetsimple_front_end/react-hooks-crud
    - npx cypress run

docker:
  stage: docker
  script:
    - cd budgetsimple_front_end/react-hooks-crud
    - docker build -t budgetsimplefrontend .
    - cd ..
    - cd ..
    - replace "F:\stela\fontys\individual\budgetsimple_individual_project\override\prod\application.properties" "F:\stela\fontys\individual\budgetsimple_individual_project\src\main\resources"
    - ./gradlew build -x test
    - docker build -t budgetsimplebackend .
    - replace "F:\stela\fontys\individual\budgetsimple_individual_project\override\test\application.properties" "F:\stela\fontys\individual\budgetsimple_individual_project\src\main\resources"
    - ./gradlew.bat --stop
