stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - cypress

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test-job:       # This job runs in the build stage, which runs first.
  stage: test
  script:
    - ./gradlew test
    - ./gradlew.bat --stop

sonarqube-check:
  stage: test
  script:
    - ./gradlew sonarqube
    - ./gradlew.bat --stop

cypress_tests:  
  stage: cypress
  image: cypress/base:10
  script:    
    - cd budgetsimple_front_end   
    - npx cypress run
